### ISSUE TITLE
Modal for adding new expense is not a great for mobile, it is covered by keyboard

### ISSUE THREAD

**Issue by hank-milliken** [pycanis/lofextra#6]
Plus modal is a really bad UI/UX pattern for mobile. It shall be a separate screen for mobile

![image](https://github.com/pycan-jouza/lofextra/assets/89867413/1d2b77d0-b6c2-4990-b134-5f936bb2c623)

**Comment by pycanis** [comment]
Hopefully improved in https://github.com/pycanis/lofextra/commit/c691bf375671f6928fe5a0d1373272ce0686d6fd
